# Machine learning

In [7]:
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
hello2 = tf.constant('Hello, TensorFlow!')
print(hello)
print(hello2)

Tensor("Const_10:0", shape=(), dtype=string)
Tensor("Const_11:0", shape=(), dtype=string)


In [8]:
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a,b)
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [11]:
sess = tf.Session()
print(sess.run(hello))
print(sess.run(c))
print(sess.run([a,b,c]))
sess.close()

b'Hello, TensorFlow!'
42
[10, 32, 42]


In [13]:
X = tf.placeholder(tf.float32, [None, 3], name="X") #[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]
print(X)

Tensor("X_2:0", shape=(?, 3), dtype=float32)


In [14]:
W = tf.Variable(tf.random_normal([3,2]))  # random_normal : 정규분포의 무작위 값으로 초기화
b = tf.Variable(tf.random_normal([2,1]))
expr = tf.matmul(X,W) + b

In [23]:
x_data = [[1,2,3], [4,5,6]] # [2,3]
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print('===x===')
print(x_data)
print('===W===')
print(sess.run(W))
print('===b===')
print(sess.run(b))
print('===expr===')
print(sess.run(expr,feed_dict={X: x_data}))
sess.close()

===x===
[[1, 2, 3], [4, 5, 6]]
===W===
[[-1.03237069  0.20677288]
 [-1.09382164 -0.55270708]
 [ 0.49115533 -0.19152613]]
===b===
[[-1.09029269]
 [-0.07344572]]
===expr===
[[-2.83684087 -2.56351233]
 [-6.72510481 -3.15904665]]


# linear regression

In [12]:
x_data = [1,2,3]
y_data = [1,2,3]
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0)) # -1.0~1.0 균등분포
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
X = tf.placeholder(tf.float32, name="X")
Y = tf.placeholder(tf.float32, name="Y")

hypothesis = W * X + b # W : 가중치, b : 편향
cost = tf.reduce_mean(tf.square(hypothesis - Y)) # http://dlwodus.tistory.com/27
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1) # 경사 하강법
train_op = optimizer.minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(100):
        _, cost_val = sess.run([train_op, cost], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, sess.run(W), sess.run(b))
    print("X: 5, Y:", sess.run(hypothesis, feed_dict={X:5}))
    print("X: 2.5, Y:", sess.run(hypothesis, feed_dict={X:2.5}))

0 25.4188 [ 0.59947586] [ 1.48819149]
1 0.579112 [ 0.37802172] [ 1.35076284]
2 0.269312 [ 0.41822964] [ 1.32940161]
3 0.253148 [ 0.42945462] [ 1.29622936]
4 0.241083 [ 0.44347191] [ 1.26520169]
5 0.229631 [ 0.45681748] [ 1.23477256]
6 0.218723 [ 0.46987879] [ 1.205091]
7 0.208333 [ 0.48262215] [ 1.17612123]
8 0.198437 [ 0.49505964] [ 1.14784813]
9 0.189011 [ 0.50719804] [ 1.12025464]
10 0.180033 [ 0.5190447] [ 1.09332454]
11 0.171482 [ 0.53060645] [ 1.06704175]
12 0.163336 [ 0.54189038] [ 1.04139078]
13 0.155578 [ 0.55290306] [ 1.01635647]
14 0.148188 [ 0.56365097] [ 0.99192399]
15 0.141148 [ 0.57414049] [ 0.96807879]
16 0.134444 [ 0.58437788] [ 0.94480681]
17 0.128058 [ 0.59436917] [ 0.92209429]
18 0.121975 [ 0.60412019] [ 0.89992774]
19 0.116181 [ 0.61363691] [ 0.87829411]
20 0.110662 [ 0.6229248] [ 0.85718054]
21 0.105406 [ 0.63198942] [ 0.83657449]
22 0.100399 [ 0.64083618] [ 0.81646383]
23 0.0956298 [ 0.64947027] [ 0.79683661]
24 0.0910873 [ 0.65789676] [ 0.77768117]
25 0.0867606 